### Modulos

Los modulos o paqueteria estan muy importante por los lenguajes de programacion, en particular para Python.

Un gran parte de las funcionalidades de base de Python estan dentro de paqueterias muy conocidas las cuales necesitan cargar.

Hay en particular varias paqueterias como **numpy** o **matplotlib** y mas reciente **pandas** que permiten hacer muchas cosas que necesitan.

**numpy** esta muy interesante par hacer la mayoria de los calculos
**matplotlib** esta muy importante para hacer todo los plots, las figuras
**pandas** esta muy util para hacer analisis de datos


Tambien hay otras paqueterias muy conocidas ahora para hacer Machine Learning, como **tensroflow**, **keras**....

### Cargar una paqueteria instalada

Vamos a usar **numpy** como ejemplo. Se requiere usar la palabra protegida _import_

In [1]:
import numpy

Eso permite importar todo lo que hay dentro de la paqueteria numpy. Por ejemplo, puedo usar la funcion de generacion de un arreglo (lo que veremos en un notebook dedicado) la cual se llama _zeros_

In [2]:
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

Se puede tambien cargar una paqueteria dentro de un objeto. Por ejemplo aqui, vamos a cargar **numpy** dentro de un objeto cual llamaremos _np_ (lo pueden llamar como quieren). Se puede usar numpy usando el nombre _np_

In [3]:
import numpy as np

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

### Cargar unicamente la funcion _zeros_ de numpy

Es posible de cargar solamente una parte de una paqueteria. Existen paqueterias las cuales suelen ser muy pesadas. Asi se puede descargar unicamente la parte la cual nos interesa.

Por eso se usa la palabra protegida _from_

In [4]:
from numpy import zeros


In [5]:
zeros(5)

array([0., 0., 0., 0., 0.])